# Generated by Django 4.2.3 on 2023-07-13 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ishchi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('last_name', models.CharField(max_length=128)),
                ('age', models.IntegerField(verbose_name='Yoshi')),
                ('salary', models.CharField(max_length=128)),
                ('position', models.CharField(max_length=128)),
            ],
        ),
    ]
