# Generated by Django 4.2.3 on 2023-07-17 14:15

import app1.models.auth
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_user_groups_user_user_permissions'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', app1.models.auth.CustomuserManager()),
            ],
        ),
    ]
