# Generated by Django 4.2.3 on 2023-07-17 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_alter_user_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='permission',
            field=models.BooleanField(default=False),
        ),
    ]
