# Generated by Django 4.2.1 on 2023-07-24 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_user_permission'),
    ]

    operations = [
        migrations.CreateModel(
            name='OTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=512)),
                ('email', models.CharField(max_length=50)),
                ('is_conf', models.BooleanField(default=False)),
                ('is_expire', models.BooleanField(default=False)),
                ('tries', models.IntegerField(default=0)),
                ('by', models.IntegerField(choices=[(1, 'Login'), (2, 'Register')])),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
