# Generated by Django 4.2.3 on 2023-07-26 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_otp_step'),
    ]

    operations = [
        migrations.AddField(
            model_name='otp',
            name='extra',
            field=models.JSONField(default={}),
        ),
    ]
